"""empty message

Revision ID: 0049171efc73
Revises: 2bf2b9ac9f57
Create Date: 2022-04-27 15:47:08.730871

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0049171efc73"
down_revision = "2bf2b9ac9f57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_datetime", table_name="notification")
    op.drop_constraint("notification_ibfk_2", "notification", type_="foreignkey")
    op.drop_column("notification", "sender_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification",
        sa.Column("sender_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "notification_ibfk_2", "notification", "user", ["sender_id"], ["id"]
    )
    op.create_index(
        "ix_notification_datetime", "notification", ["datetime"], unique=False
    )
    # ### end Alembic commands ###
