"""empty message

Revision ID: 42a6936ad12b
Revises: fd26dc9de0dd
Create Date: 2022-04-27 16:37:34.389479

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a6936ad12b'
down_revision = 'fd26dc9de0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'patient_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
