"""add ondelete

Revision ID: c91830f867a2
Revises: 0049171efc73
Create Date: 2022-04-27 16:29:04.881594

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c91830f867a2'
down_revision = '0049171efc73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointment_ibfk_1', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_ibfk_1', 'appointment', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###
