"""empty message

Revision ID: fd26dc9de0dd
Revises: c91830f867a2
Create Date: 2022-04-27 16:32:28.251301

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fd26dc9de0dd'
down_revision = 'c91830f867a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointment_ibfk_3', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('appointment_ibfk_3', 'appointment', 'patient', ['patient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
